# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=700,fmode=600"]
  else
    config.vm.synced_folder ".", "/vagrant"
  end
  config.vm.define "MACHINE01" do |d|
    d.vm.box = "bento/centos-7.6"
#   d.vm.box = "robert-hadoop-box"
#    d.vm.box = "ubuntu/xenial64"
    d.vm.hostname = "MACHINE01"
    d.vm.network "private_network", ip: "107.170.38.238"        
    d.vm.provider "virtualbox" do |v|        
      v.memory = 6144
      v.cpus = 1
    end
    d.vm.provision "shell", inline: <<-SHELL
         sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
         sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config   
         systemctl restart sshd
      SHELL
    d.vm.provision :shell, path: "scripts/post-deploy.sh"
#    d.vm.provision :shell, path: "scripts/post-deploy-ubuntu.sh"
  end  
  config.vm.define "MACHINE02" do |d| 
    d.vm.box = "robert-kafka-box" 
    d.vm.hostname = "MACHINE02"
    d.vm.network "private_network", ip: "107.170.112.81"        
    d.vm.provider "virtualbox" do |v|        
      v.memory = 3072
      v.cpus = 1
    end
    d.vm.provision "shell", inline: <<-SHELL
         sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
         sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config   
         systemctl restart sshd
      SHELL
  end  
  config.vm.define "MACHINE03" do |d| 
    d.vm.box = "robert-kafka-box" 
    d.vm.hostname = "MACHINE03"
    d.vm.network "private_network", ip: "107.170.115.161"        
    d.vm.provider "virtualbox" do |v|        
      v.memory = 3072
      v.cpus = 1
    end
    d.vm.provision "shell", inline: <<-SHELL
         sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
         sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config   
         systemctl restart sshd
      SHELL
  end  
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
    config.vbguest.no_install = true
    config.vbguest.no_remote = true
  end
end
